<?php

return [
    'profile' => [
        'name' => 'Denis Isaev',
        'name_ru' => 'Денис Исаев',
        'title' => 'Full Stack Developer',
        'title_alt' => 'Front end / Back end / Full Stack Developer',
        'location' => 'Odessa, Ukraine',
        'phone' => '0930556561',
        'email' => 'isaev.denis.igorevih@gmail.com',
        'birth_date' => '02.03.1985',
        'portfolio_url' => 'https://denbasmedium.github.io/portfolio',
        'summary' => 'Full Stack Developer adept in working in both front-end and back-end development processes. Skilled in programming design, development, and implementation of functional specifications.',
        'skills' => [
            'Critical thinking and problem solving',
            'Effective Time Management',
            'Ability to Multitask',
            'Adaptability',
            'Teamwork',
            'Leadership',
            'Communication',
        ],
        'tech_skills' => [
            'HTML & CSS',
            'Git',
            'PHP',
            'JavaScript',
            'SQL',
            'Python',
            'Django',
            'Jinja',
            'Laravel',
            'Vue.js',
            'Inertia',
            'Docker',
        ],
        'languages' => [
            ['name' => 'Russian', 'level' => 'Native'],
            ['name' => 'Ukrainian', 'level' => 'Native'],
            ['name' => 'English', 'level' => 'Fluent'],
        ],
        'education' => [
            'degree' => 'Magister of automatisation and computer-integration technologies',
            'school' => 'Odessa National Academy of Food Technologies',
            'faculty' => 'Faculty of Computer Systems and Automation',
            'period' => 'September 2003 - May 2007',
            'url' => 'https://onaft.edu.ua/en/atp',
        ],
        'experience' => [
            [
                'role' => 'Full Stack Developer',
                'company' => 'BMBY Group (DREAMS)',
                'url' => 'https://bmby.com/',
                'period' => 'January 2024 - Present',
                'points' => [
                    'Development of server software (PHP8+)',
                    'Development of the client side (JavaScript)',
                    'Writing database queries (MySql, Mongo)',
                    'Transition of projects from php5.2 to php8.3',
                    'Development of CRM modules',
                ],
            ],
            [
                'role' => 'Full Stack Developer',
                'company' => 'uk4ru.com',
                'url' => 'https://uk4ru.com/',
                'period' => 'March 2024 - March 2025',
                'points' => [
                    'Development of server software (PHP)',
                    'Development of the client side (JavaScript)',
                    'Writing database queries (MySql)',
                ],
            ],
            [
                'role' => 'Development and support of a CRM system for the Service Center',
                'company' => null,
                'url' => null,
                'period' => 'February 2023 - Present',
                'points' => [
                    'Designed and developed core CRM system features tailored to service center needs.',
                    'Integrated front-end and back-end using Laravel, Vue.js, and Inertia.js for seamless SPA functionality.',
                    'Implemented user authentication, role-based access control, and secure data management.',
                    'Optimized database queries and application performance using MySQL.',
                    'Developed RESTful APIs for third-party integrations.',
                    'Created dynamic and responsive UI components in Vue.js',
                    'Implemented Progressive Web App (PWA) features, including offline functionality and app-like user experience.',
                    'Developed and managed push notification services to improve user engagement and communication.',
                ],
            ],
            [
                'role' => 'Service center director',
                'company' => 'ITSA, Odessa',
                'url' => 'http://itsa.in.ua/',
                'period' => 'October 2015 - Present',
                'points' => [
                    'Managing the work of six branches in Odessa.',
                    'Organization of work for more than 50 employees.',
                    'Development of CRM systems and automation of business processes.',
                    'Development of telegram chat bot service @itsa_service_bot.',
                    'Development of an application to automate administration processes (Laravel, Vue.js, Chart.js, Puppeteer, Docker).',
                    'Development of multiple Python scripts for parsing, reporting, data analysis, performance metrics calculations.',
                ],
            ],
            [
                'role' => 'Consolidated Information Analyst',
                'company' => 'Regional Information and Analytical Center under the Regional State Administration of Odessa',
                'url' => null,
                'period' => 'February 2010 - February 2013',
                'points' => [
                    'Collection and analysis of large volumes of information',
                    'Writing macros and scripts to automate information collection',
                    'Creation of reports, graphs and databases',
                    'Server health support',
                    'Software installation, configuration and support',
                ],
            ],
            [
                'role' => 'Computer science teacher',
                'company' => 'STEP school, Odessa',
                'url' => null,
                'period' => 'April 2007 - September 2010',
                'points' => [
                    'Teaching the PC review course individually and in groups',
                    'Teaching a course on repairing and servicing PCs individually',
                ],
            ],
        ],
    ],

    'works' => [
        [
            'slug' => 'crm-service-center',
            'title' => 'CRM for Service Center',
            'subtitle' => 'Laravel, Vue.js, Inertia, PWA',
            'year' => '2023–Present',
            'description' => 'Full-featured CRM system for a service center with multiple branches. Includes role-based access, dashboards, PWA support, push notifications, and RESTful APIs for integrations.',
            'tech' => ['Laravel', 'Vue.js', 'Inertia.js', 'MySQL', 'PWA', 'Chart.js'],
            'url' => null,
            'screenshots' => [
                ['src' => '/works/crm1.jpg', 'alt' => 'Dashboard'],
                ['src' => '/works/crm2.jpg', 'alt' => 'Orders list'],
                ['src' => '/works/crm3.jpg', 'alt' => 'Reports'],
            ],
            'video_url' => 'https://drive.google.com/file/d/1tAfrDx5e8qrIcbDZbBSYPFmpg5MONzVY/preview',
        ],
        [
            'slug' => 'seo-ranking-checker',
            'title' => 'SEO Ranking Checker',
            'subtitle' => 'Laravel, Selenium, PHP',
            'year' => '2026',
            'description' => 'SEO Ranking Checker is a tool that allows you to check the ranking of a website in search engines.',
            'tech' => ['Laravel', 'Selenium', 'PHP'],
            'url' => null,
            'screenshots' => [
                ['src' => '/works/seo-ranking1.jpg', 'alt' => 'Dashboard'],
                ['src' => '/works/seo-ranking2.jpg', 'alt' => 'Orders list'],
                ['src' => '/works/seo-ranking3.jpg', 'alt' => 'Reports'],
            ],
            'video_url' => 'https://drive.google.com/file/d/1Sb_j1hg08FHxE4LctvBCsiePndiRVYXa/preview',
        ],
    ],

    /*
    | Certificates: add entries here. Put images in public/images/certificates/
    | Optional: 'url' — link to verify (LinkedIn Learning, Coursera, etc.)
    | To add images: open certificate page → screenshot or download → save to public/images/certificates/ with the name below.
    */
    'certificates' => [
        [
            'title' => 'PHP: Object-Oriented Programming',
            'description' => 'OOP principles for PHP: classes, inheritance, magic methods. By Kevin Skoglund.',
            'image' => '/images/certificates/01-php-oop.png',
            'year' => '2026',
            'issuer' => 'LinkedIn Learning',
            'url' => 'https://www.linkedin.com/learning/certificates/b9fce512175047e20bcd97b962542092e85c10114694cd29da11aff38368ec52',
        ],
        [
            'title' => 'Advanced PHP: Debugging Techniques',
            'description' => 'Error levels, logging, Xdebug, Laravel Tinker, remote debugging with Monolog.',
            'image' => '/images/certificates/02-php-debugging.png',
            'year' => '2026',
            'issuer' => 'LinkedIn Learning',
            'url' => 'https://www.linkedin.com/learning/certificates/482f014030f12cb3762d3823ad3571753f80a07403f95ecae6532db8d2362dd9',
        ],
        [
            'title' => 'PHP Techniques: Pagination',
            'description' => 'Paginating lists and database records in PHP, OOP approach. By Kevin Skoglund.',
            'image' => '/images/certificates/03-php-pagination.png',
            'year' => '2026',
            'issuer' => 'LinkedIn Learning',
            'url' => 'https://www.linkedin.com/learning/certificates/7a8fd6443066cef2343d2ef587bc268b94c2712b814e215297cfebfd7fabed0c',
        ],
        [
            'title' => 'Advance Your PHP Skills',
            'description' => 'Deepen your core PHP knowledge by leveraging more of the built-in functionality and libraries. Discover how to use the provided data structure, iterators, interfaces, exceptions, and classes to get the job done.',
            'image' => '/images/certificates/04-linkedin-learning.png',
            'year' => '2026',
            'issuer' => 'LinkedIn Learning',
            'url' => 'https://www.linkedin.com/learning/certificates/0a6884db740c97e2cf6117099e29420d0753b929004a85ec2bbfad6b0dc53617',
        ],
        [
            'title' => 'PHP: User Authentication',
            'description' => 'Best practices for auth in PHP: login/logout, passwords, HTTPS, securing tokens.',
            'image' => '/images/certificates/05-php-user-auth.png',
            'year' => '2026',
            'issuer' => 'LinkedIn Learning',
            'url' => 'https://www.linkedin.com/learning/certificates/57161bc0f76e986719f35f8d3645272a163d3a0bb472e237559ab75af902c9a3',
        ],
        [
            'title' => 'PHP: Creating Secure Websites',
            'description' => 'Security for PHP apps: input filtering, output escaping, XSS and SQL injection defenses.',
            'image' => '/images/certificates/06-php-secure-websites.png',
            'year' => '2026',
            'issuer' => 'LinkedIn Learning',
            'url' => 'https://www.linkedin.com/learning/certificates/654f542145f254817472959dde385799e9485dadb5cd946814e8aceefdeaa78f',
        ],
        [
            'title' => 'PHP Techniques: Working with Files and Directories',
            'description' => 'Reading/writing files, directory handling, permissions, file uploads. By Kevin Skoglund.',
            'image' => '/images/certificates/07-php-files-directories.png',
            'year' => '2026',
            'issuer' => 'LinkedIn Learning',
            'url' => 'https://www.linkedin.com/learning/certificates/1f6df82064e34872edf3e26a0d09d9df0f45480762b5f34b9591ce8135d8eb45',
        ],
        [
            'title' => 'Functional Programming with PHP',
            'description' => 'First-class functions, array operations, filter/reduce, recursion. By Shaun Wassell.',
            'image' => '/images/certificates/08-php-functional.png',
            'year' => '2026',
            'issuer' => 'LinkedIn Learning',
            'url' => 'https://www.linkedin.com/learning/certificates/9e8157304cfc7740839ece5063eec141ee523d2c84e151520b1f0c642afe68a4',
        ],
        [
            'title' => 'PHP: Testing Legacy Applications',
            'description' => 'Writing tests for legacy PHP codebases, refactoring test suites. By Chris Hartjes.',
            'image' => '/images/certificates/09-php-testing-legacy.png',
            'year' => '2026',
            'issuer' => 'LinkedIn Learning',
            'url' => 'https://www.linkedin.com/learning/certificates/15bc8db37746422d10f51fd9fab229c43079d02257dbd84b781e94dc8d553593',
        ],
        [
            'title' => 'Master Full-Stack Web Development with Laravel & PHP',
            'description' => 'Laravel from routing to auth, migrations, Eloquent, RESTful APIs, deployment. ~15 hours.',
            'image' => '/images/certificates/10-coursera-laravel-php.png',
            'year' => '2026',
            'issuer' => 'Coursera / Board Infinity',
            'url' => 'https://www.coursera.org/account/accomplishments/verify/ARNQ1N3GGQYE',
        ],
    ],
];
