<?php

return [
    'profile' => [
        'name' => 'Denis Isaev',
        'name_ru' => 'Денис Исаев',
        'title' => 'Full Stack Developer',
        'title_alt' => 'Front end / Back end / Full Stack Developer',
        'location' => 'Odessa, Ukraine',
        'phone' => '0930556561',
        'email' => 'isaev.denis.igorevih@gmail.com',
        'birth_date' => '02.03.1985',
        'portfolio_url' => 'https://denbasmedium.github.io/portfolio',
        'summary' => 'Full Stack Developer adept in working in both front-end and back-end development processes. Skilled in programming design, development, and implementation of functional specifications.',
        'skills' => [
            'Critical thinking and problem solving',
            'Effective Time Management',
            'Ability to Multitask',
            'Adaptability',
            'Teamwork',
            'Leadership',
            'Communication',
        ],
        'tech_skills' => [
            'HTML & CSS',
            'Git',
            'PHP',
            'JavaScript',
            'SQL',
            'Python',
            'Django',
            'Jinja',
            'Laravel',
            'Vue.js',
            'Inertia',
            'Docker',
        ],
        'languages' => [
            ['name' => 'Russian', 'level' => 'Native'],
            ['name' => 'Ukrainian', 'level' => 'Native'],
            ['name' => 'English', 'level' => 'Fluent'],
        ],
        'education' => [
            'degree' => 'Magister of automatisation and computer-integration technologies',
            'school' => 'Odessa National Academy of Food Technologies',
            'faculty' => 'Faculty of Computer Systems and Automation',
            'period' => 'September 2003 - May 2007',
            'url' => 'https://onaft.edu.ua/en/atp',
        ],
        'experience' => [
            [
                'role' => 'Full Stack Developer',
                'company' => 'BMBY Group (DREAMS)',
                'url' => 'https://bmby.com/',
                'period' => 'January 2024 - Present',
                'points' => [
                    'Development of server software (PHP8+)',
                    'Development of the client side (JavaScript)',
                    'Writing database queries (MySql, Mongo)',
                    'Transition of projects from php5.2 to php8.3',
                    'Development of CRM modules',
                ],
            ],
            [
                'role' => 'Full Stack Developer',
                'company' => 'uk4ru.com',
                'url' => 'https://uk4ru.com/',
                'period' => 'March 2024 - March 2025',
                'points' => [
                    'Development of server software (PHP)',
                    'Development of the client side (JavaScript)',
                    'Writing database queries (MySql)',
                ],
            ],
            [
                'role' => 'Development and support of a CRM system for the Service Center',
                'company' => null,
                'url' => null,
                'period' => 'February 2023 - Present',
                'points' => [
                    'Designed and developed core CRM system features tailored to service center needs.',
                    'Integrated front-end and back-end using Laravel, Vue.js, and Inertia.js for seamless SPA functionality.',
                    'Implemented user authentication, role-based access control, and secure data management.',
                    'Optimized database queries and application performance using MySQL.',
                    'Developed RESTful APIs for third-party integrations.',
                    'Created dynamic and responsive UI components in Vue.js',
                    'Implemented Progressive Web App (PWA) features, including offline functionality and app-like user experience.',
                    'Developed and managed push notification services to improve user engagement and communication.',
                ],
            ],
            [
                'role' => 'Service center director',
                'company' => 'ITSA, Odessa',
                'url' => 'http://itsa.in.ua/',
                'period' => 'October 2015 - Present',
                'points' => [
                    'Managing the work of six branches in Odessa.',
                    'Organization of work for more than 50 employees.',
                    'Development of CRM systems and automation of business processes.',
                    'Development of telegram chat bot service @itsa_service_bot.',
                    'Development of an application to automate administration processes (Laravel, Vue.js, Chart.js, Puppeteer, Docker).',
                    'Development of multiple Python scripts for parsing, reporting, data analysis, performance metrics calculations.',
                ],
            ],
            [
                'role' => 'Consolidated Information Analyst',
                'company' => 'Regional Information and Analytical Center under the Regional State Administration of Odessa',
                'url' => null,
                'period' => 'February 2010 - February 2013',
                'points' => [
                    'Collection and analysis of large volumes of information',
                    'Writing macros and scripts to automate information collection',
                    'Creation of reports, graphs and databases',
                    'Server health support',
                    'Software installation, configuration and support',
                ],
            ],
            [
                'role' => 'Computer science teacher',
                'company' => 'STEP school, Odessa',
                'url' => null,
                'period' => 'April 2007 - September 2010',
                'points' => [
                    'Teaching the PC review course individually and in groups',
                    'Teaching a course on repairing and servicing PCs individually',
                ],
            ],
        ],
    ],

    'works' => [
        [
            'slug' => 'crm-service-center',
            'title' => 'CRM for Service Center',
            'subtitle' => 'Laravel, Vue.js, Inertia, PWA',
            'year' => '2023–Present',
            'description' => 'Full-featured CRM system for a service center with multiple branches. Includes role-based access, dashboards, PWA support, push notifications, and RESTful APIs for integrations.',
            'tech' => ['Laravel', 'Vue.js', 'Inertia.js', 'MySQL', 'PWA', 'Chart.js'],
            'url' => null,
            'screenshots' => [
                ['src' => 'https://placehold.co/1200x800/1e293b/94a3b8?text=Dashboard', 'alt' => 'Dashboard'],
                ['src' => 'https://placehold.co/1200x800/1e293b/94a3b8?text=Orders', 'alt' => 'Orders list'],
                ['src' => 'https://placehold.co/1200x800/1e293b/94a3b8?text=Reports', 'alt' => 'Reports'],
            ],
            'video_url' => null,
        ],
    ],
];
